version: '3.8'

services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - db_data:/var/lib/mysql

volumes:
  drupal-data:
  db_data: